### ISSUE TITLE
ENH: Vectorize _random_points_sample

### ISSUE THREAD

**Issue by tastatham** [tastatham/geobootstrap#1]
To vectorize as much of the [for loop](https://github.com/tastatham/geobootstrap/blob/9a36c23239ebe787716b9ced60604cc4d3841d51/geobootstrap/utils.py#L165) in _random_points_sample

**Comment by tastatham** [comment]
Instead of vectorizing this simple random point sample method - to use @ljw's method of sampling points in geopandas/geopandas/pull/2363

**Comment by ljwolf** [comment]
(also didn't realize this repo was public now!)

**Comment by tastatham** [comment]
> (also didn't realize this repo was public now!)

yes, I should have said sorry. The JGI content is still hidden.
The areal interpolation methods I implemented are also available in the coss repo & both can be installed using pip.

**Comment by tastatham** [comment]
closed as per #4
